# Generated by Django 5.0.14 on 2026-05-29 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_payment_method'),
        ('seekers', '0006_donationrequest_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('utr', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='seekers.donationrequest')),
            ],
        ),
    ]
