# Generated by Django 6.0.5 on 2026-05-19 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hospital_name', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=200)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='medical_documents/')),
                ('document_type', models.CharField(choices=[('CERT', 'Medical Certificate'), ('ID', 'Government ID'), ('PHOTO', 'Patient Photo'), ('OTHER', 'Other Document')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='seekers.donationrequest')),
            ],
        ),
    ]
