# Generated by Django 6.0.5 on 2026-05-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
