# Generated by Django 6.0.5 on 2026-05-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0002_donationrequest_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
