# Generated by Django 6.0.5 on 2026-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0003_donationrequest_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('CERT', 'Medical Certificate'), ('ID', 'Government ID / Identity Proof'), ('BANK', 'Bank Passbook'), ('PHOTO', 'Patient Photo'), ('OTHER', 'Other Document')], max_length=10),
        ),
    ]
