# Generated by Django 6.0.5 on 2026-05-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0004_alter_medicaldocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
