# Generated by Django 6.0.5 on 2026-05-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0005_donationrequest_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
