# Generated by Django 6.0.5 on 2026-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('VERIFICATION', 'Verification & Documents'), ('PAYMENT', 'Payment / Donation Issue'), ('ACCOUNT', 'Account & Login Issue'), ('CAMPAIGN', 'Campaign Management'), ('TECHNICAL', 'Technical Support'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
