# Generated by Django 6.0.5 on 2026-05-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='subject',
        ),
    ]
